jobs:
  include:
  - stage: Linux build
    os: linux
    language: python
    sudo: required
    dist: xenial
    python: 3.6
    addons:
      apt:
        packages:
        - tesseract-ocr
        - p7zip-full
    env:
    - PY=python3
  - stage: Windows build
    os: windows
    language: shell
    python: 3.6
    env:
    - PY=py

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    ./scripts/osx_before_install.sh;
  elif  [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    ./scripts/lin_before_install.sh;
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    ./scripts/win_before_install.bat;
  fi

install:
- "$PY -m pip install -r requirements.txt"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    ./scripts/osx_install.sh;
  elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    ./scripts/lin_install.sh;
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    ./scripts/win_install.bat;
  fi

script:
- echo done


before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "hallowf"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - $PY src/_version.py --tag
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "sIp5V9SauHzRWj7ipc6MyfxARWV9yG4mgN+hvEmlnen3igjQ9VQvjRPqVUjvitgm0Q0teVlQH4nDh4f4J35no2+uupH4ZA24nf8pvoS0gTQeg5mVdapzddL+TVdvp+VPo6gbszUUBoOFDrgO9sDmgNJnMJ2OCegY4CkbJwEIH/bNqq9YmArjseUSGzhLpsqSFC7fhbxoQ/N9AHAh1zkb01cS8du5atvcYSd/YHhj2DTQ5qz8e8dbhyrmAPmRPuK/MA9j+Dgjz+Pkd7iREXHJQYsrJmLn1fOreNVZn4XOdiMsqK7I72t5/CW0ZjMQCbvw6vIms6Sv8QMwb7RuOFEN9GVbksbWPjrjyUwK3taPJaBLA50/+xQf1GAFsNlESzOCjmBbiuZyEgRp1A9z6zptL1YbohPv8+l5pgfVfNnPPQBDjdWppTORQtpCdue/l1H+PZZXpKPpRDYhJ+B4wcxUwn2o2ZIy+Ii752U1rtXgAYONe7Q+3jzRYmpbn0ZE2KmSA4hzqaYSepLEOFUVLw4JtE+HZ0kaOV+1d8CSyinszYHZ3PoneUlpNpxUWCAXJz3zOKX16+b3Py0sztVojNuhuGUaeoCdcNR0sb+lUwusgIiaxmFNAyTg3ZZ4qZg6JGyEvcDVX0tAvQwsI90ttPQEexKS6SRonyq4tJ3s9NEWDGI="
  file_glob: true
  file: src/dist/*
  on:
    repo: hallowf/STPDF
